# SVL signal configuration file
# Default required sensor state is "off" (inactive).

greeley_to_fryton:
  upper_head_address: 05.01.01.01.47.06.00.15
  lower_head_address: 05.01.01.01.47.06.00.1C

  routes:
    main:
      requirements:
      - turnout: NT176 # greeley -> fryton switch
        state: thrown  # we actually want it closed, but the switch is reversed.
      - sensor: FrytonMain
      - sensor: GreeleyFrytonSidingSwitch
      next_signal: green
      dispatch_control:
        memory_var: IMBA174  # fryton main
        direction: SB
    siding:
      is_diverging: true
      requirements:
      - turnout: NT176 # greeley -> fryton switch
        state: closed  # this is actually thrown; switch is reversed for some reason :(
      - sensor: GreeleyFrytonSidingSwitch
      - sensor: FrytonSiding
      next_signal: green
      dispatch_control:
        memory_var: IMBA177  # fryton siding
        direction: SB

#ebbetts_pass_nb_from_fryton_main:
#  normal_route:
#    requirements:
#    - turnout: NT175 # fryton -> ebbetts switch
#      state: closed
#    next_signal: green

#ebbetts_pass_nb_from_fryton_siding:
#  normal_route:
#    requirements:
#    - turnout: NT175 # fryton -> ebbetts switch
#      state: thrown
#    next_signal: green

jacksonville_nb_to_jerico:
  upper_head_address: 997
  lower_head_address: 998

  routes:
    normal:
      requirements:
      - sensor: JerichoNB
      next_signal: jerico_nb_to_kaos
      dispatch_control:
        memory_var: IMBA300
        direction: NB

kalamazoo_front_to_jerico:
  upper_head_address: 1234
  lower_head_address: 5678

  routes:
    normal:
      requirements:
      - turnout: NT325
        state: closed
      - sensor: JerichoSB
      next_signal: green # jericho_to_jacksonville_sb
      dispatch_control:
        memory_var: IMBA301  # jericho SB
        direction: SB

jerico_nb_to_kaos:
  upper_head_address: 2009
  lower_head_address: 2010

  routes:
    kaos_main_to_loop:
      requirements:
      - sensor: KaosMain
      - turnout: NT326  # kalamazoo rear track / kaos main
        state: closed # to kaos main
      - turnout: NT325  # xover
        state: closed
      - turnout: NT327 # jasper
        state: thrown
      next_signal: green
      dispatch_control:
        memory_var: IMBA331  # Loop NB
        direction: NB
    to_kalamazoo_rear:
      is_diverging: true
      maximum_speed: slow
      requirements:
      - sensor: KaosMain
      - turnout: NT326 # kalamazoo rear track / kaos main
        state: thrown
      - turnout: NT325  # xover
        state: closed
      next_signal: green

fryton_main_nb:
  upper_head_address: 2001
  lower_head_address: 2004

  routes:
    main:
      requirements:
      - turnout: NT175
        state: closed
      - sensor: FrytonMain
      next_signal: green
    siding:
      requirements:
      - turnout: NT175
        state: thrown
      - sensor: FrytonSiding
      next_signal: green

igo_to_hallelujah_sb_main:
  head_address: 05.01.01.01.47.02.00.00

  routes:
    hallelujah:
      requirements:
      - turnout: NT250
        state: thrown
      - sensor: Hallelujah
      next_signal: hallelujah_to_greeley
      dispatch_control:
        memory_var: IMBA179  # Hallelujah  Main
        direction: SB

igo_to_hallelujah_nb_main:
  head_address: 05.01.01.01.47.02.00.07

  routes:
    hallelujah:
      requirements:
      - turnout: NT250
        state: closed
      - sensor: Hallelujah
      next_signal: hallelujah_to_greeley
      dispatch_control:
        memory_var: IMBA179  # Hallelujah  Main
        direction: SB

igo_to_jacksonville_nb:
  head_address: None
  routes:
    jacksonville_nb:
      requirements:
      - sensor: JacksonvilleNB
      next_signal: jacksonville_nb_to_jerico
      dispatch_control:
        memory_var: IMBA203
        direction: NB

igo_to_jacksonville_sb:
  head_address: None
  routes:
    jacksonville_sb:
      requirements:
      - sensor: JacksonvilleSB
      next_signal: green
      dispatch_control:
        memory_var: IMBA202
        direction: SB

hemet_dwarf:
  head_address: 05.01.01.01.47.05.00.07

  routes:
    onto_main:
      is_diverging: true
      requirements:
      - turnout: NT226
        state: thrown
      # TODO: speed limit or other restriction?
      next_signal: hallelujah_to_greeley

hallelujah_to_igo:
  head_address: 05.01.01.01.47.02.00.0E

  routes:
    nb:
      requirements:
      - turnout: NT250
        state: closed
      - sensor: IgoNB
      next_signal: igo_to_jacksonville_nb
      dispatch_control:
        memory_var: IMBA252  # Igo NB
        direction: NB
    sb:
      next_signal: igo_to_jacksonville_sb
      is_diverging: true
      requirements:
      - turnout: NT250
        state: thrown
      - sensor: IgoSB
      dispatch_control:
        memory_var: IMBA253  # Igo SB
        direction: NB

fryton_main_to_greeley:
  head_address: 05.01.01.01.47.06.00.00

  routes:
    main:
      next_signal: greeley_to_hallelujah
      requirements:
      - sensor: Greeley
      - sensor: Greeley_HallelujahSide
      - sensor: GreeleyFrytonSidingSwitch
      - turnout: NT176
        state: thrown  # backwards :(
      dispatch_control:
        memory_var: IMBA178  # Greeley Main
        direction: NB


fryton_siding_to_greeley:
  head_address: 05.01.01.01.47.06.00.07

  routes:
    onto_main:
      is_diverging: true
      next_signal: greeley_to_hallelujah
      requirements:
      - sensor: Greeley
      - sensor: Greeley_HallelujahSide
      - sensor: GreeleyFrytonSidingSwitch
      - turnout: NT176
        state: closed  # backwards :(
      dispatch_control:
        memory_var: IMBA178  # Greeley Main
        direction: NB


greeley_to_hallelujah:
  upper_head_address: 05.01.01.01.47.05.00.0E
  lower_head_address: 05.01.01.01.47.05.00.15

  routes:
    to_igo:
      next_signal: hallelujah_to_igo
      requirements:
      - sensor: Hallelujah
      - turnout: NT226 # hemet
        state: closed
      - turnout: NT225 # papermill
        state: closed
      dispatch_control:
        memory_var: IMBA179  # Hallelujah Main
        direction: NB
    to_hemet:
      # next_signal: none
      is_diverging: true
      maximum_speed: slow
      requirements:
      - sensor: Hallelujah
      - turnout: NT226 # hemet
        state: thrown
      - turnout: NT225 # papermill
        state: closed
    xover_to_papermill:
      is_diverging: true
      maximum_speed: slow
      requirements:
      - turnout: NT225
        state: thrown
      next_signal: green

hallelujah_to_greeley:
  upper_head_address: 05.01.01.01.47.05.00.23
  lower_head_address: 05.01.01.01.47.05.00.1C

  routes:
    greeley:
      requirements:
      - sensor: Greeley
      - sensor: Greeley_HallelujahSide
      - turnout: NT225  # papermill
        state: closed
      next_signal: greeley_to_fryton
      dispatch_control:
        memory_var: IMBA178  # Greeley Main
        direction: SB

greeley_papermill_dwarf:
  head_address: 05.01.01.01.47.05.00.2A

  routes:
    onto_main:
      is_diverging: true
      requirements:
      - sensor: Greeley
      - turnout: NT225
        state: thrown
      next_signal: greeley_to_fryton