# SVL signal configuration file
# Default required sensor state is "off" (inactive).

greeley_to_fryton:
  upper_head_address: 05.01.01.01.47.06.00.15
  lower_head_address: 05.01.01.01.47.06.00.1C

  routes:
    main:
      requirements:
      - turnout: NT176 # greeley -> fryton switch
        state: thrown  # we actually want it closed, but the switch is reversed.
      - sensor: FrytonMain
      - sensor: GreeleyFrytonSidingSwitch
      # next_signal: green
      dispatch_control:
        memory_var: IMBA174  # fryton main
        direction: SB
    siding:
      is_diverging: true
      requirements:
      - turnout: NT176 # greeley -> fryton switch
        state: closed  # this is actually thrown; switch is reversed for some reason :(
      - sensor: GreeleyFrytonSidingSwitch
      - sensor: FrytonSiding
      # next_signal: green
      dispatch_control:
        memory_var: IMBA177  # fryton siding
        direction: SB

#ebbetts_pass_nb_from_fryton_main:
#  normal_route:
#    requirements:
#    - turnout: NT175 # fryton -> ebbetts switch
#      state: closed
#    next_signal: green

#ebbetts_pass_nb_from_fryton_siding:
#  normal_route:
#    requirements:
#    - turnout: NT175 # fryton -> ebbetts switch
#      state: thrown
#    next_signal: green

jacksonville_to_jericho_front:
  upper_head_address: 05.01.01.01.47.09.00.00
  lower_head_address: 05.01.01.01.47.09.00.07

  routes:
    normal:
      requirements:
      - sensor: JerichoSB
      - turnout: NT276  # jacksonville dark xover
        state: thrown  # reversed :(
      next_signal: jericho_to_kaos_front
      dispatch_control:
        memory_var: IMBA301
        direction: NB

jacksonville_to_jericho_rear:
  upper_head_address: 05.01.01.01.47.09.00.2A
  lower_head_address: 05.01.01.01.47.09.00.1C

  routes:
    normal:
      requirements:
      - sensor: JerichoNB
      - turnout: NT276  # jacksonville dark xover
        state: thrown  # straight thru
      next_signal: jericho_nb_to_kaos
      dispatch_control:
        memory_var: IMBA300
        direction: NB
    # dark_xover:
    #   requirements:
    #   - turnout: NT276
    #     state: closed
    #   maximum_speed: restricting
    #   is_diverging: true
    #   dispatch_control:
    #     ignore: true

jacksonville_to_igo_rear:
  lower_head_address: 05.01.01.01.47.0D.00.0E
  upper_head_address: 05.01.01.01.47.0D.00.1C

  routes:
    normal:
      requirements:
      - sensor: IgoNB
      - turnout: NT275 # jville xover, igo side
        state: thrown  # reversed
      - turnout: NT278  # jacksonville siding, igo side
        state: thrown  # reversed :(
      next_signal: igo_to_hallelujah_nb_main
    xover:
      requirements:
      - sensor: IgoSB
      - turnout: NT275
        state: closed
      - turnout: NT253  # to AQX
        state: thrown  # reversed
      next_signal: igo_to_hallelujah_sb_main
      is_diverging: true

jacksonville_to_igo_front:
  head_address: 05.01.01.01.47.0D.00.15

  routes:
    normal:
      requirements:
      - sensor: IgoSB
      - turnout: NT275 # jville xover, igo side
        state: thrown  # reversed
      - turnout: NT253  # to AQX
        state: thrown  # reversed
      next_signal: igo_to_hallelujah_sb_main

jericho_to_jacksonville_rear:
  upper_head_address: 05.01.01.01.47.09.00.15
  lower_head_address: 05.01.01.01.47.09.00.23

  routes:
    normal:
      requirements:
      - sensor: JacksonvilleNB
      - turnout: NT280
        state: closed
      - turnout: NT279  # jville siding - jericho side
        state: closed  # set to main
      - turnout: NT276  # jacksonville dark xover
        state: thrown  # straight-thru
      next_signal: jacksonville_to_igo_rear
      dispatch_control:
        memory_var: IMBA203
        direction: SB

    into_jv_siding:
      is_diverging: true
      maximum_speed: slow
      requirements:
      - turnout: NT279  # jville siding - jericho side
        state: thrown  # set to siding
      - turnout: NT276  # jacksonville dark xover
        state: thrown  # straight-thru

jericho_to_jacksonville_front:
  head_address: 05.01.01.01.47.09.00.0E

  routes:
    normal:
      requirements:
      - sensor: JacksonvilleSB
      - turnout: NT276  # jacksonville dark xover
        state: thrown  # reversed :(
      next_signal: jacksonville_to_igo_front 
      dispatch_control:
        memory_var: IMBA202
        direction: SB
    dark_xover:
      requirements:
      - turnout: NT276
        state: closed
      maximum_speed: restricting
      is_diverging: true
      dispatch_control:
        ignore: true

kalamazoo_front_to_jerico:
  upper_head_address: 1234
  lower_head_address: 5678

  routes:
    normal:
      requirements:
      - turnout: NT325
        state: closed
      - sensor: JerichoSB
      next_signal: jericho_to_jacksonville_front
      dispatch_control:
        memory_var: IMBA301  # jericho SB
        direction: SB

jericho_nb_to_kaos:
  upper_head_address: 2009
  lower_head_address: 2010

  routes:
    kaos_main_to_loop_nb:
      requirements:
      - sensor: KaosMain
      - turnout: NT326  # kalamazoo rear track / kaos main
        state: closed # to kaos main
      - turnout: NT325  # xover
        state: closed
      - turnout: NT327 # jasper
        state: thrown
      - turnout: NT328
        state: closed  # Loop NB
      # next_signal: green
      dispatch_control:
        memory_var: IMBA331  # Loop NB
        direction: NB
    kaos_main_to_loop_sb:
      requirements:
      - sensor: KaosMain
      - turnout: NT326  # kalamazoo rear track / kaos main
        state: closed # to kaos main
      - turnout: NT325  # xover
        state: closed
      - turnout: NT327 # jasper
        state: thrown
      - turnout: NT328
        state: thrown  # Loop SB
      is_diverging: true
      # next_signal: green
      dispatch_control:
        memory_var: IMBA332  # Loop SB
        direction: NB  # but going North
    to_kalamazoo_rear:
      is_diverging: true
      maximum_speed: slow
      requirements:
      - sensor: KaosMain
      - turnout: NT326 # kalamazoo rear track / kaos main
        state: thrown
      - turnout: NT325  # xover
        state: closed
      # next_signal: green

fryton_main_nb:
  upper_head_address: 2001
  lower_head_address: 2004

  routes:
    main:
      requirements:
      - turnout: NT175
        state: closed
      - sensor: FrytonMain
      #next_signal: green
    siding:
      requirements:
      - turnout: NT175
        state: thrown
      - sensor: FrytonSiding
      #3next_signal: green

igo_to_hallelujah_sb_main:
  head_address: 05.01.01.01.47.02.00.00

  routes:
    hallelujah:
      requirements:
      - turnout: NT250
        state: thrown
      - sensor: Hallelujah
      next_signal: hallelujah_to_greeley
      dispatch_control:
        memory_var: IMBA179  # Hallelujah  Main
        direction: SB

igo_to_hallelujah_nb_main:
  head_address: 05.01.01.01.47.02.00.07

  routes:
    hallelujah:
      requirements:
      - turnout: NT250
        state: closed
      - sensor: Hallelujah
      next_signal: hallelujah_to_greeley
      dispatch_control:
        memory_var: IMBA179  # Hallelujah  Main
        direction: SB
    hall_industry:
      requirements:
      - turnout: NT250
        state: thrown  # to industry
      dispatch_control:
        ignore: true
      is_diverging: true
      maximum_speed: restricting

igo_to_jacksonville_rear:
  upper_head_address: 05.01.01.01.47.0D.00.00
  lower_head_address: 05.01.01.01.47.0D.00.07
  routes:
    jville_rear_main:
      requirements:
      - sensor: JacksonvilleNB
      - turnout: NT278  # jville siding - igo side
        state: thrown  # set for main
      - turnout: NT279  # jville siding - jericho side
        state: closed # set for main
      - turnout: NT275  # jville-igo xover
        state: thrown  # set for main
      - turnout: NT276  # jville/jericho dark xover
        state: thrown  # set for main
      - turnout: NT280  # union coal
        state: closed  # main
      next_signal: jacksonville_to_jericho_rear
      dispatch_control:
        memory_var: IMBA203
        direction: NB
    jville_siding:
      is_diverging: true
      maximum_speed: slow
      requirements:
      - turnout: NT278  # jville siding - igo side
        state: closed  # set for siding
    jville_rear_main_until_siding:
      maximum_speed: restricting
      requirements:
      - sensor: JacksonvilleNB
      - turnout: NT278  # jville siding - igo side
        state: thrown  # set for main
      - turnout: NT279  # jville siding - jericho side
        state: thrown # set for siding
      - turnout: NT275  # jville-igo xover
        state: thrown  # set for main
      - turnout: NT276  # jville/jericho dark xover
        state: thrown  # set for main
    jville_rear_main_until_ucoal:
      maximum_speed: restricting
      is_diverging: true
      requirements:
      - sensor: JacksonvilleNB
      - turnout: NT278  # jville siding - igo side
        state: thrown  # set for main
      - turnout: NT279  # jville siding - jericho side
        state: closed # set for main
      - turnout: NT275  # jville-igo xover
        state: thrown  # set for main
      - turnout: NT280  # union coal
        state: thrown  # set to industry


igo_to_jacksonville_front:
  upper_head_address: 05.01.01.01.47.0D.00.31
  lower_head_address: 05.01.01.01.47.0D.00.2A

  routes:
    front_main:
      requirements:
      - sensor: JacksonvilleSB
      - turnout: NT253  # to AQX
        state: thrown  # set to main
      - turnout: NT275  # xover
        state: thrown  # actually normal
      - turnout: NT276  # jville/jericho dark xover
        state: thrown  # set for main
      next_signal: jacksonville_to_jericho_front
      dispatch_control:
        memory_var: IMBA202
        direction: SB
    xover_to_rear_main:
      is_diverging: true
      requirements:
      - sensor: JacksonvilleNB
      - turnout: NT253  # to AQX
        state: thrown  # set to main
      - turnout: NT275  # xover
        state: closed  # actually xover
      - turnout: NT276  # jville/jericho dark xover
        state: thrown  # set for main
      next_signal: jacksonville_to_jericho_rear
    to_aqx:
      is_diverging: true
      maximum_speed: restricting
      requirements:
      - turnout: NT253  # to AQX
        state: closed  # set to AQX

hemet_dwarf:
  head_address: 05.01.01.01.47.05.00.07

  routes:
    onto_main:
      is_diverging: true
      requirements:
      - turnout: NT226
        state: thrown
      # TODO: speed limit or other restriction?
      next_signal: hallelujah_to_greeley

hallelujah_to_igo:
  upper_head_address: 05.01.01.01.47.02.00.0E
  lower_head_address: 05.01.01.01.47.02.00.15

  routes:
    nb:
      requirements:
      - turnout: NT250
        state: closed
      - sensor: IgoNB
      - turnout: NT251  # dark xover igo-hallelujah
        state: thrown  # straight thru
      next_signal: igo_to_jacksonville_nb
      dispatch_control:
        memory_var: IMBA252  # Igo NB
        direction: NB
    sb:
      next_signal: igo_to_jacksonville_sb
      is_diverging: true
      requirements:
      - turnout: NT250
        state: thrown
      - sensor: IgoSB
      - turnout: NT251  # dark xover igo-hallelujah
        state: thrown  # straight thru
      dispatch_control:
        memory_var: IMBA253  # Igo SB
        direction: NB

fryton_main_to_greeley:
  head_address: 05.01.01.01.47.06.00.00

  routes:
    main:
      next_signal: greeley_to_hallelujah
      requirements:
      - sensor: Greeley
      - sensor: Greeley_HallelujahSide
      - sensor: GreeleyFrytonSidingSwitch
      - turnout: NT176
        state: thrown  # backwards :(
      dispatch_control:
        memory_var: IMBA178  # Greeley Main
        direction: NB


fryton_siding_to_greeley:
  head_address: 05.01.01.01.47.06.00.07

  routes:
    onto_main:
      is_diverging: true
      next_signal: greeley_to_hallelujah
      requirements:
      - sensor: Greeley
      - sensor: Greeley_HallelujahSide
      - sensor: GreeleyFrytonSidingSwitch
      - turnout: NT176
        state: closed  # backwards :(
      dispatch_control:
        memory_var: IMBA178  # Greeley Main
        direction: NB


greeley_to_hallelujah:
  upper_head_address: 05.01.01.01.47.05.00.0E
  lower_head_address: 05.01.01.01.47.05.00.15

  routes:
    to_igo:
      next_signal: hallelujah_to_igo
      requirements:
      - sensor: Hallelujah
      - turnout: NT226 # hemet
        state: closed
      - turnout: NT225 # papermill
        state: closed
      dispatch_control:
        memory_var: IMBA179  # Hallelujah Main
        direction: NB
    to_hemet:
      # next_signal: none
      is_diverging: true
      maximum_speed: slow
      requirements:
      - sensor: Hallelujah
      - turnout: NT226 # hemet
        state: thrown
      - turnout: NT225 # papermill
        state: closed
    xover_to_papermill:
      is_diverging: true
      maximum_speed: slow
      requirements:
      - turnout: NT225
        state: thrown
      # next_signal: green

hallelujah_to_greeley:
  upper_head_address: 05.01.01.01.47.05.00.23
  lower_head_address: 05.01.01.01.47.05.00.1C

  routes:
    greeley:
      requirements:
      - sensor: Greeley
      - sensor: Greeley_HallelujahSide
      - turnout: NT225  # papermill
        state: closed
      next_signal: greeley_to_fryton
      dispatch_control:
        memory_var: IMBA178  # Greeley Main
        direction: SB

greeley_papermill_dwarf:
  head_address: 05.01.01.01.47.05.00.2A

  routes:
    onto_main:
      is_diverging: true
      requirements:
      - sensor: Greeley
      - turnout: NT225
        state: thrown
      next_signal: greeley_to_fryton