# SVL signal configuration file
# Default required sensor state is "off" (inactive).

fryton_main_sb:
  upper_head_address: 2002
  lower_head_address: 2003

  dispatch_control:
    memory_var: IMBA174
    direction: SB
  normal_route:
    requirements:
    - turnout: NT176 # greeley -> fryton switch
      state: thrown  # we actually want it closed, but the switch is reversed.
    - sensor: LS174  # fryton main
    - sensor: LS176  # fryton siding switch (greeley side)
    next_signal: ebbetts_pass_sb_from_fryton_main
  diverging_route:
    requirements:
    - turnout: NT176 # greeley -> fryton switch
      state: closed  # this is actually thrown; switch is reversed for some reason :(
    - sensor: LS176  # fryton siding switch (greeley side)
    - sensor: LS177  # fryton siding
    next_signal: ebbetts_pass_sb_from_fryton_siding

#ebbetts_pass_nb_from_fryton_main:
#  normal_route:
#    requirements:
#    - turnout: NT175 # fryton -> ebbetts switch
#      state: closed
#    next_signal: green

#ebbetts_pass_nb_from_fryton_siding:
#  normal_route:
#    requirements:
#    - turnout: NT175 # fryton -> ebbetts switch
#      state: thrown
#    next_signal: green

jericho_nb:
  upper_head_address: 997
  lower_head_address: 998

  dispatch_control:
    memory_var: IMBA300
    direction: NB

  normal_route:
    requirements:
    - sensor: LS207  # jericho nb
    next_signal: KaosB

KaosA:
  upper_head_address: 1234
  lower_head_address: 5678

  dispatch_control:
    memory_var: IMBA302
    direction: SB

  normal_route:
    requirements:
    - turnout: NT325
      state: closed
    - sensor: LS204  # jericho sb
    next_signal: green

KaosB:
  upper_head_address: 2009
  lower_head_address: 2010

  dispatch_control:
    memory_var: IMBA330
    direction: NB

  normal_route:
    requirements:
    - sensor: LS205  # kaos main
    - turnout: NT326
      state: thrown # to kaos main
    - turnout: NT325  # xover
      state: closed
    next_signal: green
  diverging_route:
    requirements:
    - sensor: LS205  # kaos main
    - turnout: NT326
      state: closed  # "thru" route is modeled as "normal" turnout, even though it's diverging.
    - turnout: NT325  # xover
      state: closed
    next_signal: green

fryton_main_nb:
  upper_head_address: 2001
  lower_head_address: 2004

  normal_route:
    requirements:
    - turnout: NT175
      state: closed
    - sensor: LS174  # fryton main
    next_signal: green
  diverging_route:
    requirements:
    - turnout: NT175
      state: thrown
    - sensor: LS177  # fryton siding
    next_signal: green

hallelujah_main_nb_paper:
  upper_head_address: 2005
  lower_head_address: 2006

  dispatch_control:
    memory_var: IMBA179
    direction: NB

  normal_route:
    requirements:
    - turnout: NT225
      state: closed
    next_signal: green

  diverging_route:
    requirements:
    - turnout: NT225
      state: thrown
    - turnout: NT227
      state: thrown
    next_signal: green

hallelujah_to_igo:
  upper_head_address: 05.01.01.01.47.01.00.07
  lower_head_address: 05.01.01.01.47.01.00.00

  normal_route:
    requirements:
    - turnout: NT250
      state: closed

  diverging_route:
    requirements:
    - turnout: NT250
      state: thrown

  next_signal: green