# SVL signal configuration file
# Default required sensor state is "off" (inactive).

fryton_main_sb:
  upper_head_address: 2002
  lower_head_address: 2003

  dispatch_control:
    memory_var: IMBA174
    direction: SB
  normal_route:
    requirements:
    - turnout: NT176 # greeley -> fryton switch
      state: thrown  # we actually want it closed, but the switch is reversed.
    - sensor: FrytonMain  # fryton main
    - sensor: GreeleyFrytonMainSwitch  # fryton siding switch (greeley side)
    next_signal: green
  diverging_route:
    requirements:
    - turnout: NT176 # greeley -> fryton switch
      state: closed  # this is actually thrown; switch is reversed for some reason :(
    - sensor: GreeleyFrytonMainSwitch  # fryton siding switch (greeley side)
    - sensor: FrytonSiding  # fryton siding
    next_signal: green

#ebbetts_pass_nb_from_fryton_main:
#  normal_route:
#    requirements:
#    - turnout: NT175 # fryton -> ebbetts switch
#      state: closed
#    next_signal: green

#ebbetts_pass_nb_from_fryton_siding:
#  normal_route:
#    requirements:
#    - turnout: NT175 # fryton -> ebbetts switch
#      state: thrown
#    next_signal: green

jericho_nb:
  upper_head_address: 997
  lower_head_address: 998

  dispatch_control:
    memory_var: IMBA300
    direction: NB

  normal_route:
    requirements:
    - sensor: JerichoNB
    next_signal: KaosB

KaosA:
  upper_head_address: 1234
  lower_head_address: 5678

  dispatch_control:
    memory_var: IMBA302
    direction: SB

  normal_route:
    requirements:
    - turnout: NT325
      state: closed
    - sensor: JerichoSB
    next_signal: green # jericho_to_jacksonville_sb

KaosB:
  upper_head_address: 2009
  lower_head_address: 2010

  dispatch_control:
    memory_var: IMBA330
    direction: NB

  normal_route:
    requirements:
    - sensor: KaosMain
    - turnout: NT326
      state: thrown # to kaos main
    - turnout: NT325  # xover
      state: closed
    next_signal: green
  diverging_route:
    requirements:
    - sensor: KaosMain
    - turnout: NT326
      state: closed  # "thru" route is modeled as "normal" turnout, even though it's diverging.
    - turnout: NT325  # xover
      state: closed
    next_signal: green

fryton_main_nb:
  upper_head_address: 2001
  lower_head_address: 2004

  normal_route:
    requirements:
    - turnout: NT175
      state: closed
    - sensor: FrytonMain
    next_signal: green
  diverging_route:
    requirements:
    - turnout: NT175
      state: thrown
    - sensor: FrytonSiding
    next_signal: green

hallelujah_main_nb_paper:
  upper_head_address: 2005
  lower_head_address: 2006

  dispatch_control:
    memory_var: IMBA179
    direction: NB

  normal_route:
    requirements:
    - turnout: NT225
      state: closed
    - sensor: Hallelujah
    next_signal: hallelujah_to_igo

  diverging_route:
    requirements:
    - turnout: NT225
      state: thrown
    - turnout: NT227
      state: thrown
    next_signal: green

igo_to_hallelujah_sb_main:
  head_address: 05.01.01.01.47.02.00.00

  normal_route:
    requirements:
    - turnout: NT250
      state: thrown
    - sensor: Hallelujah
    next_signal: hallelujah_to_greeley

igo_to_hallelujah_nb_main:
  head_address: 05.01.01.01.47.02.00.07

  normal_route:
    requirements:
    - turnout: NT250
      state: closed
    - sensor: Hallelujah
    next_signal: hallelujah_to_greeley

igo_to_jacksonville_nb:
  head_address: None
  normal_route:
    requirements:
    - sensor: Jacksonville NB
    next_signal: jericho_nb

igo_to_jacksonville_sb:
  head_address: None
  normal_route:
    requirements:
    - sensor: Jacksonville SB
    next_signal: green

hemet_dwarf:
  head_address: 05.01.01.01.47.05.00.07
  normal_route:
    requirements:
    - turnout: NT226
      state: thrown
    - sensor: Hallelujah
    next_signal: hallelujah_to_greeley

hallelujah_to_greeley:
  head_address: None
  normal_route:
    requirements:
    - sensor: Greeley
    - sensor: Greeley_HallelujahSide
    next_signal: fryton_main_sb

hallelujah_to_igo:
  head_address: 05.01.01.01.47.02.00.0E

  dispatch_control:
    memory_var: IMTA250A
    direction: NB

  normal_route:
    requirements:
    - turnout: NT250
      state: closed
    - sensor: Igo NB
    next_signal: igo_to_jacksonville_nb

  diverging_route:
    requirements:
    - turnout: NT250
      state: thrown
    - sensor: Igo SB
    next_signal: igo_to_jacksonville_sb

greeley_to_hallelujah:
  upper_head_address: 05.01.01.01.47.05.00.0E
  lower_head_address: 05.01.01.01.47.05.00.15

  normal_route:
    requirements:
    - sensor: Hallelujah
    next_signal: hallelujah_to_igo

hallelujah_to_greeley:
  upper_head_address: 05.01.01.01.47.05.00.23
  lower_head_address: 05.01.01.01.47.05.00.1C

  normal_route:
    requirements:
      - sensor: Greeley
    next_signal: fryton_main_sb

greeley_papermill_dwarf:
  head_address: 05.01.01.01.47.05.00.2A

  normal_route:
    requirements:
    - sensor: Greeley
    - turnout: NT225
      state: thrown